from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Tuple


@dataclass(frozen=True)
class LegendConfig:
    dpi: int = 600
    footer_band_ratio: float = 0.25
    icon_scale: float = 1.6
    padding_px: int = 10
    icon_search_scale_w: float = 3.0
    icon_search_scale_h: float = 2.4
    icon_size_min_ratio: float = 0.6
    icon_size_max_ratio: float = 3.2
    icon_merge_pad_ratio: float = 0.35
    tight_crop_pad_ratio: float = 0.1
    icon_edge_pad_ratio: float = 0.12
    legend_side_score_ratio: float = 1.12
    legend_side_min_votes: int = 3
    icon_iou_dedupe_threshold: float = 0.25
    icon_outlier_min_ratio: float = 0.75
    icon_edge_outlier_ratio: float = 0.9
    icon_post_pad_ratio: float = 0.12
    min_ink_ratio: float = 0.01
    max_ink_ratio: float = 0.55
    component_min_area_ratio: float = 0.004
    component_max_area_ratio: float = 0.45
    component_aspect_min: float = 0.4
    component_aspect_max: float = 2.6
    line_merge_tol: float = 0.008  # fraction of page height
    use_ocr_fallback: bool = True
    tesseract_cmd: str | None = None
    debug: bool = False
    ocr_preprocess: bool = True
    ocr_fallback_min_labels: int = 3
    ocr_fuzzy_ratio: float = 0.78
    icon_output_scale: float = 3.0
    icon_output_sharpen: bool = True
    debug_crops: bool = True


# Canonical labels
ALLOWED_LABELS: List[str] = [
    "milk",
    "gluten",
    "egg",
    "fish",
    "soy",
    "sesame",
    "mustard",
    "nuts",
    "peanut",
    "shellfish",
    "molluscs",
    "crustacean",
    "celery",
    "lupin",
    "sulphites",
    "mushroom",
    "signature_dish",
    "veg",
    "non_veg",
]

# Multi-token phrases -> canonical label
PHRASE_SYNONYMS: Dict[Tuple[str, ...], str] = {
    ("non", "vegetarian"): "non_veg",
    ("non", "vegeterian"): "non_veg",
    ("non", "vegitarian"): "non_veg",
    ("non", "vegan"): "non_veg",
    ("non", "veg"): "non_veg",
    ("plant", "based"): "veg",
    ("tree", "nut"): "nuts",
    ("tree", "nuts"): "nuts",
    ("ground", "nut"): "peanut",
    ("ground", "nuts"): "peanut",
    ("mustard", "seed"): "mustard",
    ("mustard", "seeds"): "mustard",
    ("sesame", "seed"): "sesame",
    ("sesame", "seeds"): "sesame",
    ("soya", "beans"): "soy",
    ("soy", "beans"): "soy",
    ("soya", "bean"): "soy",
    ("shell", "fish"): "shellfish",
    ("shell", "fishes"): "shellfish",
    ("cereals", "containing", "gluten"): "gluten",
    ("contains", "gluten"): "gluten",
    ("contains", "milk"): "milk",
    ("contains", "egg"): "egg",
    ("contains", "soy"): "soy",
    ("contains", "sesame"): "sesame",
    ("contains", "mustard"): "mustard",
    ("contains", "nuts"): "nuts",
    ("contains", "peanut"): "peanut",
    ("contains", "peanuts"): "peanut",
    ("mollusc", "shellfish"): "molluscs",
    ("molluscs",): "molluscs",
    ("mollusk",): "molluscs",
    ("mollusk", "shellfish"): "molluscs",
    ("mollusks", "shellfish"): "molluscs",
    ("crustacean", "shellfish"): "crustacean",
    ("crustaceans", "shellfish"): "crustacean",
    ("soy", "bean"): "soy",
    ("soya", "bean"): "soy",
    ("sulphur", "dioxide"): "sulphites",
    ("sulfur", "dioxide"): "sulphites",
    ("sulfer", "dioxide"): "sulphites",
    ("sulpher", "dioxide"): "sulphites",
    ("sulphar", "dioxide"): "sulphites",
    ("sulphur", "di", "oxide"): "sulphites",
    ("sulfur", "di", "oxide"): "sulphites",
    ("sulfer", "di", "oxide"): "sulphites",
    ("sulpher", "di", "oxide"): "sulphites",
    ("sulphur", "dioxde"): "sulphites",
    ("sulfur", "dioxde"): "sulphites",
    ("sulpher", "dioxde"): "sulphites",
    ("sulfer", "dioxde"): "sulphites",
    ("sulphur", "dioxyde"): "sulphites",
    ("sulfur", "dioxyde"): "sulphites",
    ("sulfur", "dioxide", "so2"): "sulphites",
    ("sulphur", "dioxide", "so2"): "sulphites",
    ("sulfur", "dioxide", "sulfites"): "sulphites",
    ("sulphur", "dioxide", "sulphites"): "sulphites",
    ("sulphites", "so2"): "sulphites",
    ("sulfites", "so2"): "sulphites",
    ("signature", "dish"): "signature_dish",
}

# Single tokens -> canonical label
TOKEN_SYNONYMS: Dict[str, str] = {
    "milk": "milk",
    "dairy": "milk",
    "lactose": "milk",
    "lactoseintolerance": "milk",
    "casein": "milk",
    "whey": "milk",
    "wheypowder": "milk",
    "milksolids": "milk",
    "milkpowder": "milk",
    "dairymilk": "milk",
    "cream": "milk",
    "cheese": "milk",
    "butter": "milk",
    "ghee": "milk",
    "yogurt": "milk",
    "yoghurt": "milk",
    "ganache": "milk",
    "mascarpone": "milk",
    "mozzarella": "milk",
    "parmesan": "milk",
    "ricotta": "milk",
    "custard": "milk",
    "gluten": "gluten",
    "glutten": "gluten",
    "gluteen": "gluten",
    "gluton": "gluten",
    "glutin": "gluten",
    "glutinous": "gluten",
    "glutenous": "gluten",
    "wheatgluten": "gluten",
    "celiac": "gluten",
    "coeliac": "gluten",
    "wheat": "gluten",
    "barley": "gluten",
    "rye": "gluten",
    "semolina": "gluten",
    "farina": "gluten",
    "bulgur": "gluten",
    "couscous": "gluten",
    "spelt": "gluten",
    "flour": "gluten",
    "bread": "gluten",
    "pasta": "gluten",
    "muffin": "gluten",
    "cookie": "gluten",
    "cookies": "gluten",
    "crumb": "gluten",
    "crumbs": "gluten",
    "crumble": "gluten",
    "cracker": "gluten",
    "crackers": "gluten",
    "naan": "gluten",
    "roti": "gluten",
    "kulcha": "gluten",
    "paratha": "gluten",
    "parota": "gluten",
    "parotta": "gluten",
    "parotha": "gluten",
    "focaccia": "gluten",
    "egg": "egg",
    "eggs": "egg",
    "eggwhite": "egg",
    "eggyolk": "egg",
    "albumen": "egg",
    "albumin": "egg",
    "ovo": "egg",
    "fish": "fish",
    "finfish": "fish",
    "anchovy": "fish",
    "anchovies": "fish",
    "sardine": "fish",
    "sardines": "fish",
    "mackerel": "fish",
    "halibut": "fish",
    "tilapia": "fish",
    "salmon": "fish",
    "tuna": "fish",
    "bass": "fish",
    "cod": "fish",
    "trout": "fish",
    "soy": "soy",
    "soya": "soy",
    "soja": "soy",
    "soyabean": "soy",
    "soyabeans": "soy",
    "soyabeen": "soy",
    "soyabeens": "soy",
    "soybean": "soy",
    "soybeans": "soy",
    "edamame": "soy",
    "tofu": "soy",
    "sesame": "sesame",
    "sesameseed": "sesame",
    "sesameseeds": "sesame",
    "tahini": "sesame",
    "til": "sesame",
    "mustard": "mustard",
    "mustardseed": "mustard",
    "mustardseeds": "mustard",
    "rai": "mustard",
    "kadhi": "mustard",
    "kasundi": "mustard",
    "nut": "nuts",
    "nuts": "nuts",
    "treenut": "nuts",
    "treenuts": "nuts",
    "almond": "nuts",
    "almonds": "nuts",
    "walnut": "nuts",
    "walnuts": "nuts",
    "pecan": "nuts",
    "pecans": "nuts",
    "cashew": "nuts",
    "cashews": "nuts",
    "pistachio": "nuts",
    "pistachios": "nuts",
    "hazelnut": "nuts",
    "hazelnuts": "nuts",
    "macadamia": "nuts",
    "macadamias": "nuts",
    "brazilnut": "nuts",
    "brazilnuts": "nuts",
    "pinenut": "nuts",
    "pinenuts": "nuts",
    "peanut": "peanut",
    "peanuts": "peanut",
    "groundnut": "peanut",
    "groundnuts": "peanut",
    "arachis": "peanut",
    "shellfish": "shellfish",
    "shellfishes": "shellfish",
    "bivalve": "shellfish",
    "bivalves": "shellfish",
    "bivalvia": "shellfish",
    "mollusc": "molluscs",
    "molluscs": "molluscs",
    "mollusk": "molluscs",
    "mollusks": "molluscs",
    "mussels": "molluscs",
    "oysters": "molluscs",
    "clams": "molluscs",
    "scallops": "molluscs",
    "octopus": "molluscs",
    "squid": "molluscs",
    "calamari": "molluscs",
    "cuttlefish": "molluscs",
    "snail": "molluscs",
    "escargot": "molluscs",
    "abalone": "molluscs",
    "crustacean": "crustacean",
    "crustaceans": "crustacean",
    "crustacea": "crustacean",
    "prawn": "crustacean",
    "prawns": "crustacean",
    "shrimp": "crustacean",
    "shrimps": "crustacean",
    "lobster": "crustacean",
    "crab": "crustacean",
    "crabs": "crustacean",
    "celery": "celery",
    "celeriac": "celery",
    "lupin": "lupin",
    "lupine": "lupin",
    "so2": "sulphites",
    "sulphite": "sulphites",
    "sulphites": "sulphites",
    "sulfite": "sulphites",
    "sulfites": "sulphites",
    "sulphate": "sulphites",
    "sulphates": "sulphites",
    "sulfate": "sulphites",
    "sulfates": "sulphites",
    "sulphurdioxide": "sulphites",
    "sulfurdioxide": "sulphites",
    "sulpherdioxide": "sulphites",
    "sulphardioxide": "sulphites",
    "sulphurdioxde": "sulphites",
    "sulfurdioxde": "sulphites",
    "sulpherdioxde": "sulphites",
    "sulferdioxide": "sulphites",
    "sulferdioxde": "sulphites",
    "sulphurdioxides": "sulphites",
    "sulfurdioxides": "sulphites",
    "sulpherdioxides": "sulphites",
    "sulphited": "sulphites",
    "sulfited": "sulphites",
    "mushroom": "mushroom",
    "mushrooms": "mushroom",
    "signature": "signature_dish",
    "signaturedish": "signature_dish",
    "chefspecial": "signature_dish",
    "speciality": "signature_dish",
    "specialty": "signature_dish",
    "special": "signature_dish",
    "vegan": "veg",
    "vgn": "veg",
    "veggie": "veg",
    "vegitarian": "veg",
    "vegeterian": "veg",
    "plantbased": "veg",
    "nveg": "non_veg",
    "vegetarian": "veg",
    "veg": "veg",
    "nonveg": "non_veg",
    "nonvegetarian": "non_veg",
    "nonvegeterian": "non_veg",
    "nonvegitarian": "non_veg",
    "non-veg": "non_veg",
}

KEYWORDS = set(ALLOWED_LABELS) | set(TOKEN_SYNONYMS.keys())
